apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  db_user: dXNlcm5hbWU=           
  db_password: cGFzc3dvcmQ=       
  db_name: bXlzcWxfZGI=           
  db_root_password: cm9vdC1wYXNzd29yZA==
